### NumPy 自测
https://zhuanlan.zhihu.com/p/428297522

##### 将 NumPy 导入为 np，并查看版本

In [1]:
import numpy as np
np.__version__

'1.23.5'

##### 创建数字从 0 到 9 的 1 维数组

In [10]:
# a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# a = np.linspace(start=0, stop=9, num=10)
a = np.arange(start=0, stop=10, step=1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 创建所有 True 的 3×3 NumPy 数组

In [12]:
# np.bool((3, 3), True)
np.ones((3, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

##### 从 arr 中提取所有奇数

In [16]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# np.where(arr % 2 != 0, 1, 0)
arr = arr[arr % 2 == 1]
# arr = arr[arr > 1]
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

##### 将 arr 中的所有奇数替换成 -1

In [18]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

##### 将 arr 中所有奇数替换成 -1，且不改变 arr

In [21]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
out = np.where(arr % 2 == 1, -1, arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 将 1 维数组转换成 2 维数组（两行）

In [32]:
arr = np.arange(10)
# arr = arr.reshape(2, 5)
arr = arr.reshape(2, -1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


##### 垂直堆叠数组 a 和 b

In [2]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a, b)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


###### Method 1

In [5]:
arr = np.concatenate((a, b), axis=0)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


###### Method 2 & 3

In [11]:
np.vstack([a, b])
# np.hstack([a, b])
np.r_[a, b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

##### 水平堆叠数组 a 和 b

In [15]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# (1) concatenate
np.concatenate((a, b), axis=1)
# (2) horizontal stack
np.hstack([a, b])
# (3) column_
np.c_[a, b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

##### 在不使用硬编码的前提下创建以下模式。仅使用 NumPy 函数和以下输入数组 a
a = np.array([1,2,3])
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [23]:
a = np.array([1,2,3])
# arr = np.concatenate((a,a,a), axis=0).reshape(3,3)
# arr = np.r_[np.transpose(arr), arr]
# print(arr.reshape(-1))


## Standard Solution
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

##### 获取数组 a 和 b 中的共同项

In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Standard Solution
print(np.intersect1d(a, b))

[2 4]


##### 从数组 a 中移除出现在数组 b 中的所有项

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Standard Solution
print(np.setdiff1d(a, b))

[1 2 3 4]


##### 获取数组 a 和 b 中匹配元素的位置

In [37]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Standard Solution
print(np.where(a==b))

(array([1, 3, 5, 7]),)


##### 从数组 a 中提取 5 和 10 之间的所有项

In [45]:
a = np.arange(15)
# 1.
idx = np.where((a >= 5) & (a <= 10))
print(a[idx])

# 2.
# idx = np.where(np.logical_and(a>=5, a<=10))
# print(a[idx])

# 3.
# a[(a>= 5)& (a<=10)]

[ 5  6  7  8  9 10]


##### !转换函数 maxx，使其从只能对比标量而变为对比两个数组

In [47]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y


pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

##### 在数组 arr 中交换列 1 和列 2

In [51]:
arr = np.arange(9).reshape(3,3)
arr[:, (1, 0, 2)]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

##### 在数组 arr 中交换行 1 和行 2

In [53]:
arr = np.arange(9).reshape(3,3)
arr[(1, 0, 2), :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

##### 反转 2D 数组 arr 中的所有行

In [64]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

##### 反转 2D 数组 arr 中的所有列

In [69]:
arr = np.arange(9).reshape(3,3)
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [83]:
# 列表推导式 list comprehension
np.array([list(each[::-1]) for each in arr])

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

##### 创建一个形态为 5×3 的 2 维数组，包含 5 和 10 之间的随机十进制小数

In [85]:
np.random.randn()

TypeError: 'module' object is not callable